title: "[Possible Bug] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        Not sure if it's a bug? Discuss it here first. If confirmed, a maintainer will convert this to an issue.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe what you observed.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
      description: What should have happened instead?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, browser info, or any other helpful details.
