name: Feature Request
description: Suggest a feature or improvement for Knowz
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand the problem you're trying to solve.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's frustrating or missing?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Have you considered other solutions or workarounds?

  - type: textarea
    id: context
    attributes:
      label: Use case
      description: Describe your use case. How would this feature fit into your workflow?

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other context, mockups, or screenshots.
